name: OneMap SG Building Data Update

on:
  schedule:
    - cron: "0 0 15 * *" # Run on the 15th day of each month at midnight UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  update-onemap-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests tqdm aiohttp nest_asyncio asyncio logging

      - name: Get current date
        id: date
        run: echo "date=$(date +'%d%m%Y')" >> $GITHUB_OUTPUT

      - name: Create necessary directories
        run: |
          mkdir -p data
          mkdir -p logs

      - name: Download and process OneMap data
        run: |
          # Run download script with logging
          python scripts/onemap_building_download.py \
            --output_file "data/onemap_${{ steps.date.outputs.date }}.csv" \
            2>&1 | tee logs/download_${{ steps.date.outputs.date }}.log

      - name: Compare with previous data
        run: |
          python scripts/onemap_building_compare.py \
            --previous_file "data/onemap_04042025.csv" \
            --current_file "data/onemap_${{ steps.date.outputs.date }}.csv" \
            --diff_output "data/differences_onemap_04042025-${{ steps.date.outputs.date }}.csv" \
            2>&1 | tee logs/compare_${{ steps.date.outputs.date }}.log

      - name: Process and correct differences
        run: |
          python scripts/onemap_building_correct.py \
            --input_file "data/differences_onemap_04042025-${{ steps.date.outputs.date }}.csv" \
            --output_file "data/correction_differences_onemap_04042025-${{ steps.date.outputs.date }}.csv" \
            2>&1 | tee logs/correct_${{ steps.date.outputs.date }}.log

      # Use the latest version of upload-artifact to fix previous issues
      - name: Archive all results
        uses: actions/upload-artifact@v4
        with:
          name: onemap-building-data-${{ github.run_id }}
          path: |
            data/onemap_${{ steps.date.outputs.date }}.csv
            data/differences_onemap_04042025-${{ steps.date.outputs.date }}.csv
            data/correction_differences_onemap_04042025-${{ steps.date.outputs.date }}.csv
            data/differences_onemap_04042025-${{ steps.date.outputs.date }}_report.txt
            data/error_log.txt
            logs/*.log
          retention-days: 30

      - name: Commit results to repository
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'

          # Check git status before any changes
          echo "======= Git Status Before ======="
          git status

          # Get timestamp from previous step
          TIMESTAMP="${{ steps.date.outputs.date }}"
          PREV_DATE="04042025"

          # Check for OneMap data files to commit
          if [ -f "data/onemap_${TIMESTAMP}.csv" ]; then
            # Check if we have a difference file
            DIFF_FILE="data/differences_onemap_${PREV_DATE}-${TIMESTAMP}.csv"
            
            # Add files individually, making sure they exist first
            git add "data/onemap_${TIMESTAMP}.csv"
            echo "Added data/onemap_${TIMESTAMP}.csv"
            
            if [ -f "$DIFF_FILE" ]; then
              git add "$DIFF_FILE"
              echo "Added $DIFF_FILE"
              
              # Add report file if it exists
              REPORT_FILE="data/differences_onemap_${PREV_DATE}-${TIMESTAMP}_report.txt"
              if [ -f "$REPORT_FILE" ]; then
                git add "$REPORT_FILE"
                echo "Added $REPORT_FILE"
              fi
              
              # Add corrected difference file if it exists
              CORR_FILE="data/correction_differences_onemap_${PREV_DATE}-${TIMESTAMP}.csv"
              if [ -f "$CORR_FILE" ]; then
                git add "$CORR_FILE"
                echo "Added $CORR_FILE"
              fi
            fi
            
            # Add error log if it exists
            if [ -f "data/error_log.txt" ]; then
              git add "data/error_log.txt"
              echo "Added data/error_log.txt"
            fi
            
            # Add log files individually (don't use wildcard)
            for log_file in logs/download_${TIMESTAMP}.log logs/compare_${TIMESTAMP}.log logs/correct_${TIMESTAMP}.log; do
              if [ -f "$log_file" ]; then
                git add "$log_file"
                echo "Added $log_file"
              fi
            done
            
            # Check git status again
            echo "======= Git Status After Adding Files ======="
            git status
            
            # Commit with informative message
            if [ -f "$DIFF_FILE" ]; then
              git commit -m "Update OneMap building data ${TIMESTAMP} with differences from ${PREV_DATE}" || echo "No changes to commit"
            else
              git commit -m "Add new OneMap building data ${TIMESTAMP}" || echo "No changes to commit"
            fi
            
            # Try push
            echo "======= Git Push ======="
            git push origin main
            
            # Store the push result
            PUSH_RESULT=$?
            
            # If push fails, try again with pull-push sequence
            if [ $PUSH_RESULT -ne 0 ]; then
              echo "First push failed, trying pull-then-push sequence..."
              git pull --rebase origin main || echo "Pull failed"
              git push origin main
              
              # Store the second push result
              PUSH_RESULT=$?
              
              # If still fails, try with force option as last resort
              if [ $PUSH_RESULT -ne 0 ]; then
                echo "Trying force push as fallback..."
                git push -f origin main || echo "Force push also failed"
              fi
            fi
            
            echo "Successfully committed OneMap building data files"
          else
            echo "No OneMap data file found for today (${TIMESTAMP})"
          fi
